version: 0.2    
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless deploy --verbose --stage $env
      
      #test
      - mkdir artifacts
      - serverless package --package artifacts/stg --stage stg -v
      
artifacts:
  files:
    - artifacts/**/*
    - serverless.yml
    - deploy.sh
