version: 0.2    
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless deploy --verbose
      
      #test
      - mkdir artifacts
      - serverless package --package artifacts/stg --stage stg -v
