version: 0.1
phases:
  install:
    commands:
      - npm install -g serverless
  build:
    commands:
      – cd nj2jp/serverless && npm install
  post_build:
    commands:
      – serverless deploy
